In [1]:
import ast
import re
import pandas as pd

In [2]:
def read_schedules(file_name):
    raw = open(file_name).read()

    # Extract all [[...]] groups
    lists = re.findall(r'\[\[.*?\]\]', raw)

    all_records = []
    max_length = 0

    for l in lists:
        parsed = ast.literal_eval(l)
        if len(parsed)>max_length:
            max_length = len(parsed)

    for l in lists:
        parsed = ast.literal_eval(l)
        if (len(parsed)<(max_length)):
            continue
        for item in parsed:
            all_records.append({'iteration': item[0], 'objective': item[1]})

    df = pd.DataFrame(all_records)
    return df

In [7]:
df = read_schedules("best_schedule.txt")
df.describe()

       iteration   objective
count  16.000000   16.000000
mean   13.937500  198.937500
std     4.479118    7.628619
min     8.000000  189.000000
25%    10.500000  194.000000
50%    14.000000  198.000000
75%    17.500000  204.250000
max    20.000000  214.000000

In [6]:
df2 = read_schedules("best_schedule_weak_update.txt")
df2.describe()

       iteration   objective
count  12.000000   12.000000
mean   18.500000  196.583333
std     3.450955    5.599648
min    12.000000  187.000000
25%    17.000000  195.500000
50%    19.000000  197.000000
75%    21.000000  199.000000
max    23.000000  205.000000

In [8]:
read_schedules("best_schedule_5_weak_update.txt").describe()

       iteration   objective
count  11.000000   11.000000
mean    6.181818  103.909091
std     4.935953    4.846742
min     2.000000   97.000000
25%     3.000000  100.000000
50%     5.000000  104.000000
75%     7.000000  107.500000
max    18.000000  111.000000

In [9]:
read_schedules("best_schedule_5.txt").describe()

       iteration   objective
count  30.000000   30.000000
mean    4.533333  115.466667
std     6.796213    3.892817
min     0.000000  104.000000
25%     0.250000  114.000000
50%     1.000000  117.000000
75%     7.250000  118.500000
max    20.000000  119.000000